### ISSUE TITLE
about code 

### ISSUE THREAD

**Issue by helloworld-101** [salehinejad/LiteHAR#1]
Hello, your code is very powerful and has helped me a lot. Do you have the code for the other comparison experiments in the litehar paper, and if it is convenient, can you send it to me by email (my email is 3289933499@qq.com), thank you very much

**Comment by salehinejad** [comment]
The LSTM codes are here:

https://github.com/ermongroup/Wifi_Activity_Recognition

Could not find the others, so used the numbers reported in their papers.
